#!/bin/bash

#install option to install dependencies
if [ "$1" == "install" ]; then

    if ! command -v node &> /dev/null; then #checks for node.js 
        sudo apt update > /dev/null 2>&1
        sudo apt install -y nodejs > /dev/null 2>&1
    fi

    if ! command -v npm &> /dev/null; then #checks for npm
        sudo apt install -y npm > /dev/null 2>&1
    fi

    npm install > /dev/null 2>&1

    npm install dotenv > /dev/null 2>&1

    npm install winston > /dev/null 2>&1

    npm install shelljs > /dev/null 2>&1

    npm install isomorphic-git > /dev/null 2>&1

    npm install axios > /dev/null 2>&1

    npm install jest > /dev/null 2>&1

    # sudo apt install jest

    npm i --save-dev @types/jest > /dev/null 2>&1

    echo "8 dependencies installed..."

    exit 0
fi

#test option to run our testing file
if [ "$1" == "test" ]; then
    # Run Jest tests
    npx jest --coverage --json --outputFile=coverage/testResults.json
    # Compile the coverageReport.ts file to JavaScript using tsc
    npx tsc ./src/coverageReport.ts
    # Run the compiled JavaScript file (coverageReport.js)
    node ./src/coverageReport.js
    exit 0
fi

#assuming its not install or test, and SOME argument is passed
#we will assume it is a filepath and verify in our main.ts file
if [ -n "$1" ]; then
    npx tsc ./src/main.ts
    node ./src/main.js "$1"
    exit 0
fi

#if no argument is passed, exit 1 for error and print message
echo "error, no arguments passed"

exit 1