#!/bin/bash

echo "starting"

#install option to install dependencies
if [ "$1" == "install" ]; then
    echo "installing dependencies"

    if ! command -v node &> /dev/null; then #checks for node.js 
        echo "node js not found, installing time!"
        sudo apt update
        sudo apt install -y nodejs
    fi
    echo "node js found!"

    if ! command -v npm &> /dev/null; then #checks for npm
        echo "npm not found, installing time!"
        sudo apt install -y npm
    fi
    echo "npm found!"

    npm install

    npm install dotenv

    exit 0
fi

#test option to run our testing file
if [ "$1" == "test" ]; then
    npx tsc ./src/test.ts
    node ./src/test.js
    exit 0
fi

#assuming its not install or test, and SOME argument is passed
#we will assume it is a filepath and verify in our main.ts file
if [ -n "$1" ]; then
    npx tsc ./src/main.ts
    node ./src/main.js "$1"
    exit 0
fi

#if no argument is passed, exit 1 for error and print message
echo "error, no arguments passed"

exit 1